# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ishan-chhabra/ICPodSpecs.git'

target 'ICConfettiExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ICConfettiExample
  pod 'ICConfetti'

end
